# Generated by Django 5.1.3 on 2024-11-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "primer_nombre",
                    models.CharField(max_length=50, verbose_name="Primer nombre"),
                ),
                (
                    "segundo_nombre",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Segundo nombre",
                    ),
                ),
                (
                    "primer_apellido",
                    models.CharField(max_length=50, verbose_name="Primer apellido"),
                ),
                (
                    "segundo_apellido",
                    models.CharField(max_length=50, verbose_name="Segundo apellido"),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Correo"
                    ),
                ),
                (
                    "calle",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Calle"
                    ),
                ),
                (
                    "numero_exterior",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Numero exterior",
                    ),
                ),
                (
                    "numero_interior",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Numero interior",
                    ),
                ),
                (
                    "colonia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Colonia"
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Codigo postal",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ciudad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pais"
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de nacimiento"
                    ),
                ),
                (
                    "genero",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                        null=True,
                        verbose_name="Genero",
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Soltero"),
                            ("C", "Casado"),
                            ("D", "Divorciado"),
                            ("V", "Viudo"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Estado civil",
                    ),
                ),
                (
                    "escolaridad",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Primaria"),
                            ("S", "Secundaria"),
                            ("B", "Bachillerato"),
                            ("L", "Licenciatura"),
                            ("M", "Maestria"),
                            ("D", "Doctorado"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Escolaridad",
                    ),
                ),
            ],
        ),
    ]
