# Generated by Django 5.1.3 on 2024-11-15 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="fecha_creacion",
            field=models.DateField(
                auto_now_add=True, null=True, verbose_name="Fecha de creacion"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_modificacion",
            field=models.DateField(
                auto_now=True, null=True, verbose_name="Fecha de modificacion"
            ),
        ),
    ]
