# Generated by Django 5.1.3 on 2024-11-15 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habilidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "habilitado",
                    models.BooleanField(default=True, verbose_name="Habilitado"),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Titulo")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "salario_minimo",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario minimo"
                    ),
                ),
                (
                    "salario_maximo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Salario maximo",
                    ),
                ),
                (
                    "escolaridad_minima",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("P", "Primaria"),
                            ("S", "Secundaria"),
                            ("B", "Bachillerato"),
                            ("L", "Licenciatura"),
                            ("M", "Maestria"),
                            ("D", "Doctorado"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Escolaridad minima",
                    ),
                ),
                (
                    "experiencia_minima",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Experiencia minima"
                    ),
                ),
                (
                    "habilitado",
                    models.BooleanField(default=True, verbose_name="Habilitado"),
                ),
                ("fecha_creacion", models.DateField(auto_now_add=True)),
                ("fecha_modificacion", models.DateField(auto_now=True)),
                (
                    "habilidades",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="puestos.habilidad",
                        verbose_name="Habilidades",
                    ),
                ),
            ],
        ),
    ]
