# Generated by Django 5.1.3 on 2024-11-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("puestos", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="habilidad",
            options={"verbose_name": "Habilidad", "verbose_name_plural": "Habilidades"},
        ),
        migrations.AlterModelOptions(
            name="puesto",
            options={"verbose_name": "Puesto", "verbose_name_plural": "Puestos"},
        ),
        migrations.AlterField(
            model_name="puesto",
            name="habilidades",
            field=models.ManyToManyField(
                blank=True, to="puestos.habilidad", verbose_name="Habilidades"
            ),
        ),
    ]
