# Generated by Django 5.1.3 on 2024-11-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "descripcion",
                    models.TextField(blank=True, null=True, verbose_name="Descripcion"),
                ),
                (
                    "calle",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Calle"
                    ),
                ),
                (
                    "numero_exterior",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Numero exterior",
                    ),
                ),
                (
                    "numero_interior",
                    models.CharField(
                        blank=True,
                        max_length=10,
                        null=True,
                        verbose_name="Numero interior",
                    ),
                ),
                (
                    "colonia",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Colonia"
                    ),
                ),
                (
                    "codigo_postal",
                    models.CharField(
                        blank=True,
                        max_length=5,
                        null=True,
                        verbose_name="Codigo postal",
                    ),
                ),
                (
                    "ciudad",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Ciudad"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Estado"
                    ),
                ),
                (
                    "pais",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Pais"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "correo",
                    models.EmailField(
                        blank=True, max_length=100, null=True, verbose_name="Correo"
                    ),
                ),
                (
                    "gerente",
                    models.IntegerField(blank=True, null=True, verbose_name="Gerente"),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Presupuesto mensual",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateField(
                        auto_now_add=True, null=True, verbose_name="Fecha de creacion"
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateField(
                        auto_now=True, null=True, verbose_name="Fecha de modificacion"
                    ),
                ),
            ],
        ),
    ]
